; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[bean][subdir] = "contrib"
projects[bean][version] = "1.7"

projects[bean_panels][subdir] = "contrib"
projects[bean_panels][version] = "1.3"

projects[block_class][subdir] = "contrib"
projects[block_class][version] = "2.1"

projects[blockreference][subdir] = "contrib"
projects[blockreference][version] = "1.16"

projects[breakpoints][subdir] = "contrib"
projects[breakpoints][version] = "1.2"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.0"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.14"

projects[context][subdir] = "contrib"
projects[context][version] = "3.2"

projects[delta][subdir] = "contrib"
projects[delta][version] = "3.0-beta11"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.6"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[epsacrop][subdir] = "contrib"
projects[epsacrop][version] = "2.2"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.4"

projects[fieldable_panels_panes][subdir] = "contrib"
projects[fieldable_panels_panes][version] = "1.5"

projects[picture][subdir] = "contrib"
projects[picture][version] = "1.5"

projects[follow][subdir] = "contrib"
projects[follow][version] = "2.0-alpha1"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4"

projects[insert][subdir] = "contrib"
projects[insert][version] = "1.3"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[less][subdir] = "contrib"
projects[less][version] = "3.0"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[nice_menus][subdir] = "contrib"
projects[nice_menus][version] = "2.5"

projects[oauth][subdir] = "contrib"
projects[oauth][version] = "3.2"

projects[omega_tools][subdir] = "contrib"
projects[omega_tools][version] = "3.0-rc4"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[responsive_menus][subdir] = "contrib"
projects[responsive_menus][version] = "1.5"

projects[site_map][subdir] = "contrib"
projects[site_map][version] = "1.2"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][version] = "2.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[token_filter][subdir] = "contrib"
projects[token_filter][version] = "1.1"

projects[twitter][subdir] = "contrib"
projects[twitter][version] = "5.8"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.20"

projects[wp_blog][subdir] = "contrib"
projects[wp_blog][version] = "1.1"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.0"

; Themes
projects[omega][version] = "3.1"

; Libraries
libraries[lessphp][download][type] = "git"
libraries[lessphp][download][url] = "https://github.com/tea2sugars/lessphp/tree/v0.3.9"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

